# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../ui_files/mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 878)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.content_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.content_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.content_tab.setObjectName("content_tab")
        self.tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tab.setPalette(palette)
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.search_pb.setObjectName("search_pb")
        self.verticalLayout.addWidget(self.search_pb)
        self.stop_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.stop_pb.setObjectName("stop_pb")
        self.verticalLayout.addWidget(self.stop_pb)
        self.notSureSpell_chb = QtWidgets.QCheckBox(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.notSureSpell_chb.setPalette(palette)
        self.notSureSpell_chb.setAutoFillBackground(True)
        self.notSureSpell_chb.setObjectName("notSureSpell_chb")
        self.verticalLayout.addWidget(self.notSureSpell_chb)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.basicSearchType_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.basicSearchType_cb.setObjectName("basicSearchType_cb")
        self.basicSearchType_cb.addItem("")
        self.basicSearchType_cb.addItem("")
        self.verticalLayout.addWidget(self.basicSearchType_cb)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.queryLanguage_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.queryLanguage_cb.setObjectName("queryLanguage_cb")
        self.verticalLayout.addWidget(self.queryLanguage_cb)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.queryCategory_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.queryCategory_cb.setObjectName("queryCategory_cb")
        self.verticalLayout.addWidget(self.queryCategory_cb)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.resultsStop_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.resultsStop_sb.setReadOnly(False)
        self.resultsStop_sb.setMinimum(1)
        self.resultsStop_sb.setMaximum(10000)
        self.resultsStop_sb.setProperty("value", 100)
        self.resultsStop_sb.setObjectName("resultsStop_sb")
        self.verticalLayout.addWidget(self.resultsStop_sb)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.scrapWebsites_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.scrapWebsites_sb.setReadOnly(False)
        self.scrapWebsites_sb.setMinimum(1)
        self.scrapWebsites_sb.setMaximum(7)
        self.scrapWebsites_sb.setProperty("value", 5)
        self.scrapWebsites_sb.setObjectName("scrapWebsites_sb")
        self.verticalLayout.addWidget(self.scrapWebsites_sb)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gogPageFrom_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.gogPageFrom_sb.setMinimum(1)
        self.gogPageFrom_sb.setMaximum(30)
        self.gogPageFrom_sb.setObjectName("gogPageFrom_sb")
        self.verticalLayout.addWidget(self.gogPageFrom_sb)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_12.setPalette(palette)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.gogPageTo_sb = QtWidgets.QSpinBox(self.groupBox_2)
        self.gogPageTo_sb.setPrefix("")
        self.gogPageTo_sb.setMinimum(1)
        self.gogPageTo_sb.setMaximum(30)
        self.gogPageTo_sb.setObjectName("gogPageTo_sb")
        self.verticalLayout.addWidget(self.gogPageTo_sb)
        self.settings_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.settings_pb.setObjectName("settings_pb")
        self.verticalLayout.addWidget(self.settings_pb)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.fileName_le = QtWidgets.QLineEdit(self.tab)
        self.fileName_le.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.fileName_le.setFont(font)
        self.fileName_le.setObjectName("fileName_le")
        self.gridLayout_2.addWidget(self.fileName_le, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.status_la = QtWidgets.QLabel(self.groupBox)
        self.status_la.setGeometry(QtCore.QRect(10, 60, 67, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.status_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.status_la.setFont(font)
        self.status_la.setObjectName("status_la")
        self.resultLinks_la = QtWidgets.QLabel(self.groupBox)
        self.resultLinks_la.setGeometry(QtCore.QRect(10, 150, 111, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.resultLinks_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.resultLinks_la.setFont(font)
        self.resultLinks_la.setObjectName("resultLinks_la")
        self.statusVal_la = QtWidgets.QLabel(self.groupBox)
        self.statusVal_la.setGeometry(QtCore.QRect(80, 60, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusVal_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.statusVal_la.setFont(font)
        self.statusVal_la.setObjectName("statusVal_la")
        self.resultLinksVal_la = QtWidgets.QLabel(self.groupBox)
        self.resultLinksVal_la.setGeometry(QtCore.QRect(120, 150, 61, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.resultLinksVal_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.resultLinksVal_la.setFont(font)
        self.resultLinksVal_la.setObjectName("resultLinksVal_la")
        self.SearchedLinks_la = QtWidgets.QLabel(self.groupBox)
        self.SearchedLinks_la.setGeometry(QtCore.QRect(10, 90, 121, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.SearchedLinks_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SearchedLinks_la.setFont(font)
        self.SearchedLinks_la.setObjectName("SearchedLinks_la")
        self.searchedLinksVal_la = QtWidgets.QLabel(self.groupBox)
        self.searchedLinksVal_la.setGeometry(QtCore.QRect(140, 90, 81, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.searchedLinksVal_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.searchedLinksVal_la.setFont(font)
        self.searchedLinksVal_la.setObjectName("searchedLinksVal_la")
        self.time_la = QtWidgets.QLabel(self.groupBox)
        self.time_la.setGeometry(QtCore.QRect(10, 120, 51, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.time_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.time_la.setFont(font)
        self.time_la.setObjectName("time_la")
        self.timeVal_la = QtWidgets.QLabel(self.groupBox)
        self.timeVal_la.setGeometry(QtCore.QRect(60, 120, 61, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.timeVal_la.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.timeVal_la.setFont(font)
        self.timeVal_la.setObjectName("timeVal_la")
        self.anim_fr4 = QtWidgets.QFrame(self.groupBox)
        self.anim_fr4.setGeometry(QtCore.QRect(10, 30, 21, 21))
        self.anim_fr4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_fr4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_fr4.setObjectName("anim_fr4")
        self.anim_fr = QtWidgets.QFrame(self.groupBox)
        self.anim_fr.setGeometry(QtCore.QRect(130, 30, 21, 21))
        self.anim_fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_fr.setObjectName("anim_fr")
        self.anim_fr3 = QtWidgets.QFrame(self.groupBox)
        self.anim_fr3.setGeometry(QtCore.QRect(50, 30, 21, 21))
        self.anim_fr3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_fr3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_fr3.setObjectName("anim_fr3")
        self.anim_fr2 = QtWidgets.QFrame(self.groupBox)
        self.anim_fr2.setGeometry(QtCore.QRect(90, 30, 21, 21))
        self.anim_fr2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.anim_fr2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.anim_fr2.setObjectName("anim_fr2")
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.results_tw = QtWidgets.QTableWidget(self.tab)
        self.results_tw.setObjectName("results_tw")
        self.results_tw.setColumnCount(4)
        self.results_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.results_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_tw.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.results_tw, 1, 1, 2, 1)
        self.content_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 92, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tab_2.setPalette(palette)
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(80, 0))
        self.frame.setBaseSize(QtCore.QSize(100, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.downloadAdd_pb = QtWidgets.QPushButton(self.frame)
        self.downloadAdd_pb.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui files/pics/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadAdd_pb.setIcon(icon)
        self.downloadAdd_pb.setAutoDefault(False)
        self.downloadAdd_pb.setDefault(False)
        self.downloadAdd_pb.setFlat(False)
        self.downloadAdd_pb.setObjectName("downloadAdd_pb")
        self.gridLayout_4.addWidget(self.downloadAdd_pb, 0, 0, 1, 1)
        self.downloadResume_pb = QtWidgets.QPushButton(self.frame)
        self.downloadResume_pb.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ui files/pics/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadResume_pb.setIcon(icon1)
        self.downloadResume_pb.setAutoDefault(False)
        self.downloadResume_pb.setDefault(False)
        self.downloadResume_pb.setFlat(False)
        self.downloadResume_pb.setObjectName("downloadResume_pb")
        self.gridLayout_4.addWidget(self.downloadResume_pb, 0, 1, 1, 1)
        self.downloadDelete_pb = QtWidgets.QPushButton(self.frame)
        self.downloadDelete_pb.setObjectName("downloadDelete_pb")
        self.gridLayout_4.addWidget(self.downloadDelete_pb, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.downloads_tw = QtWidgets.QTableWidget(self.tab_2)
        self.downloads_tw.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.downloads_tw.setObjectName("downloads_tw")
        self.downloads_tw.setColumnCount(6)
        self.downloads_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.downloads_tw.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.downloads_tw, 1, 0, 1, 1)
        self.content_tab.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.content_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.content_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_pb.setText(_translate("MainWindow", "Search"))
        self.stop_pb.setText(_translate("MainWindow", "Stop "))
        self.notSureSpell_chb.setText(_translate("MainWindow", "Not sure about file name spell"))
        self.label_2.setText(_translate("MainWindow", "Search Type"))
        self.basicSearchType_cb.setItemText(0, _translate("MainWindow", "Google Regular Query"))
        self.basicSearchType_cb.setItemText(1, _translate("MainWindow", "Google Advanced Query"))
        self.label_6.setText(_translate("MainWindow", "query language"))
        self.label.setText(_translate("MainWindow", "Category"))
        self.label_4.setText(_translate("MainWindow", "Stop search after :"))
        self.label_3.setText(_translate("MainWindow", "Websites at sametime"))
        self.label_7.setText(_translate("MainWindow", "google pages\n"
"from"))
        self.label_12.setText(_translate("MainWindow", "to"))
        self.settings_pb.setText(_translate("MainWindow", "Settings"))
        self.fileName_le.setPlaceholderText(_translate("MainWindow", "File Name"))
        self.status_la.setText(_translate("MainWindow", "status : "))
        self.resultLinks_la.setText(_translate("MainWindow", "Results Links :"))
        self.statusVal_la.setText(_translate("MainWindow", "inactive"))
        self.resultLinksVal_la.setText(_translate("MainWindow", "0"))
        self.SearchedLinks_la.setText(_translate("MainWindow", "Searched Links :"))
        self.searchedLinksVal_la.setText(_translate("MainWindow", "0"))
        self.time_la.setText(_translate("MainWindow", "Time : "))
        self.timeVal_la.setText(_translate("MainWindow", "0"))
        item = self.results_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.results_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Download"))
        item = self.results_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Browser"))
        item = self.results_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Visit Website"))
        self.content_tab.setTabText(self.content_tab.indexOf(self.tab), _translate("MainWindow", "Scraper"))
        self.downloadAdd_pb.setText(_translate("MainWindow", "Add"))
        self.downloadResume_pb.setText(_translate("MainWindow", "Resume / Download"))
        self.downloadDelete_pb.setText(_translate("MainWindow", "Delete"))
        item = self.downloads_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.downloads_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.downloads_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.downloads_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Percentage"))
        item = self.downloads_tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Downloaded"))
        item = self.downloads_tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Last Try"))
        self.content_tab.setTabText(self.content_tab.indexOf(self.tab_2), _translate("MainWindow", "Download Manger"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

