# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 549)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 191, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addLanguage_rb = QtWidgets.QRadioButton(self.frame)
        self.addLanguage_rb.setObjectName("addLanguage_rb")
        self.gridLayout_2.addWidget(self.addLanguage_rb, 0, 0, 1, 1)
        self.addExtension_rb = QtWidgets.QRadioButton(self.frame)
        self.addExtension_rb.setObjectName("addExtension_rb")
        self.gridLayout_2.addWidget(self.addExtension_rb, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.language_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.language_le.setEnabled(False)
        self.language_le.setObjectName("language_le")
        self.verticalLayout_2.addWidget(self.language_le)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.extensionCategory_cb = QtWidgets.QComboBox(self.groupBox_4)
        self.extensionCategory_cb.setEnabled(False)
        self.extensionCategory_cb.setObjectName("extensionCategory_cb")
        self.verticalLayout_3.addWidget(self.extensionCategory_cb)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.extensions_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.extensions_le.setEnabled(False)
        self.extensions_le.setReadOnly(True)
        self.extensions_le.setObjectName("extensions_le")
        self.verticalLayout_3.addWidget(self.extensions_le)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.addExt_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.addExt_rb.setObjectName("addExt_rb")
        self.verticalLayout_3.addWidget(self.addExt_rb)
        self.removeExt_rb = QtWidgets.QRadioButton(self.groupBox_4)
        self.removeExt_rb.setObjectName("removeExt_rb")
        self.verticalLayout_3.addWidget(self.removeExt_rb)
        self.newExtension_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.newExtension_le.setEnabled(False)
        self.newExtension_le.setObjectName("newExtension_le")
        self.verticalLayout_3.addWidget(self.newExtension_le)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 1, 3, 1)
        self.addCategory_rb = QtWidgets.QRadioButton(self.frame)
        self.addCategory_rb.setObjectName("addCategory_rb")
        self.gridLayout_2.addWidget(self.addCategory_rb, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.newCategory_le = QtWidgets.QLineEdit(self.groupBox)
        self.newCategory_le.setEnabled(False)
        self.newCategory_le.setObjectName("newCategory_le")
        self.verticalLayout.addWidget(self.newCategory_le)
        self.gridLayout_2.addWidget(self.groupBox, 3, 0, 1, 1)
        self.changeAdvancedQuery_rb = QtWidgets.QRadioButton(self.frame)
        self.changeAdvancedQuery_rb.setObjectName("changeAdvancedQuery_rb")
        self.gridLayout_2.addWidget(self.changeAdvancedQuery_rb, 4, 0, 1, 1)
        self.changeQuery_rb = QtWidgets.QRadioButton(self.frame)
        self.changeQuery_rb.setCheckable(True)
        self.changeQuery_rb.setObjectName("changeQuery_rb")
        self.gridLayout_2.addWidget(self.changeQuery_rb, 4, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.advancedQuery_le = QtWidgets.QLineEdit(self.groupBox_5)
        self.advancedQuery_le.setEnabled(False)
        self.advancedQuery_le.setObjectName("advancedQuery_le")
        self.verticalLayout_4.addWidget(self.advancedQuery_le)
        self.gridLayout_2.addWidget(self.groupBox_5, 5, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.changeQuery_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.changeQuery_le.setEnabled(False)
        self.changeQuery_le.setObjectName("changeQuery_le")
        self.gridLayout.addWidget(self.changeQuery_le, 3, 0, 1, 2)
        self.changeCategory_cb = QtWidgets.QComboBox(self.groupBox_3)
        self.changeCategory_cb.setEnabled(False)
        self.changeCategory_cb.setObjectName("changeCategory_cb")
        self.gridLayout.addWidget(self.changeCategory_cb, 2, 0, 1, 1)
        self.changeLanguage_cb = QtWidgets.QComboBox(self.groupBox_3)
        self.changeLanguage_cb.setEnabled(False)
        self.changeLanguage_cb.setObjectName("changeLanguage_cb")
        self.gridLayout.addWidget(self.changeLanguage_cb, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 5, 1, 1, 1)
        self.save_pb = QtWidgets.QPushButton(self.frame)
        self.save_pb.setObjectName("save_pb")
        self.gridLayout_2.addWidget(self.save_pb, 6, 0, 1, 1)
        self.reset_pb = QtWidgets.QPushButton(self.frame)
        self.reset_pb.setObjectName("reset_pb")
        self.gridLayout_2.addWidget(self.reset_pb, 6, 1, 1, 1)
        self.cancel_pb = QtWidgets.QPushButton(self.frame)
        self.cancel_pb.setObjectName("cancel_pb")
        self.gridLayout_2.addWidget(self.cancel_pb, 7, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.addCategory_rb.toggled['bool'].connect(self.newCategory_le.setEnabled)
        self.addLanguage_rb.toggled['bool'].connect(self.language_le.setEnabled)
        self.changeQuery_rb.toggled['bool'].connect(self.changeCategory_cb.setEnabled)
        self.changeQuery_rb.toggled['bool'].connect(self.changeLanguage_cb.setEnabled)
        self.changeQuery_rb.toggled['bool'].connect(self.changeQuery_le.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.extensionCategory_cb.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.extensions_le.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.newExtension_le.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.addExt_rb.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.removeExt_rb.setEnabled)
        self.addExtension_rb.toggled['bool'].connect(self.removeExt_rb.setEnabled)
        self.changeAdvancedQuery_rb.toggled['bool'].connect(self.advancedQuery_le.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.addLanguage_rb.setText(_translate("Dialog", "Add Langugage"))
        self.addExtension_rb.setText(_translate("Dialog", "Add extension"))
        self.label_6.setText(_translate("Dialog", "New Language :"))
        self.label_2.setText(_translate("Dialog", "Category: "))
        self.label_7.setText(_translate("Dialog", "Extensions :"))
        self.label_8.setText(_translate("Dialog", "new Extension :"))
        self.addExt_rb.setText(_translate("Dialog", "Add"))
        self.removeExt_rb.setText(_translate("Dialog", "Remove"))
        self.addCategory_rb.setText(_translate("Dialog", "Add Category"))
        self.label.setText(_translate("Dialog", "New Category :"))
        self.changeAdvancedQuery_rb.setText(_translate("Dialog", "Change Advaced Query"))
        self.changeQuery_rb.setText(_translate("Dialog", "Change Query"))
        self.label_4.setText(_translate("Dialog", "Advanced Query :"))
        self.label_5.setText(_translate("Dialog", "Language :"))
        self.label_3.setText(_translate("Dialog", "Category :"))
        self.save_pb.setText(_translate("Dialog", "Save"))
        self.reset_pb.setText(_translate("Dialog", "Reset"))
        self.cancel_pb.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

